<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<AssemblyName>LINE翻译多开业绩长虹版</AssemblyName>
		<Version>2.0.1</Version>
		<AssemblyVersion>2.0.1.0</AssemblyVersion>
		<FileVersion>2.0.1.0</FileVersion>
		<ApplicationIcon>Assets\app.ico</ApplicationIcon>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\app.ico" />
		<None Remove="Assets\line.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="11.0.0-preview.6.26359.118" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\line.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Extensions\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LineTranslate.Update\LineTranslate.Update.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\app.ico" />
	</ItemGroup>

</Project>
